import Mathlib

/-!
# Section 3.1: Functional View of Distinguishing Games

This file follows Section 3.1 of "Revisiting Multi-User Lifting Theorems for
Information-Theoretic Security".  It deliberately contains no PRP/PRF-specific
definitions: systems, query functions, transcripts, and distinguishers form the
abstract layer on which concrete games are built.
-/

namespace InformationTheoreticSecurity.Section31

universe u v

/-- `X⁺`: a nonempty finite sequence, represented by its head and tail. -/
abbrev NonemptyHistory (X : Type u) := X × List X

namespace NonemptyHistory

def toList (xs : NonemptyHistory X) : List X := xs.1 :: xs.2

def last (xs : NonemptyHistory X) : X :=
  (toList xs).getLast (by simp [toList])

def ofList (xs : List X) (h : xs ≠ []) : NonemptyHistory X :=
  match xs with
  | [] => False.elim (h rfl)
  | x :: tail => (x, tail)

@[simp]
theorem toList_ofList (xs : List X) (h : xs ≠ []) :
    toList (ofList xs h) = xs := by
  cases xs with
  | nil => exact False.elim (h rfl)
  | cons x tail => rfl

end NonemptyHistory

/-- An `(X,Y)`-system is a total response function `X⁺ → Y`. -/
abbrev System (X : Type u) (Y : Type v) := NonemptyHistory X → Y

/-- A system is stateless when only the last query affects its response. -/
def Stateless (S : System X Y) : Prop :=
  ∃ f : X → Y, ∀ xs, S xs = f (NonemptyHistory.last xs)

/-- Embed an ordinary function as a stateless system. -/
def statelessSystem (f : X → Y) : System X Y :=
  fun xs => f (NonemptyHistory.last xs)

@[simp]
theorem stateless_statelessSystem (f : X → Y) :
    Stateless (statelessSystem f) := ⟨f, fun _ => rfl⟩

/-- A random system is a probability distribution over total systems. -/
abbrev RandomSystem (X : Type u) (Y : Type v) := PMF (System X Y)

/-- The random stateless system induced by a distribution on functions. -/
noncomputable def randomStatelessSystem (F : PMF (X → Y)) :
    RandomSystem X Y := F.map statelessSystem

/-- A partial query function `Y⁺ ⇀ X`, represented by `Option`. -/
structure QueryFunction (X : Type u) (Y : Type v) where
  next : List Y → Option X
  prefixClosed : ∀ {pre history : List Y} {x : X},
    pre <+: history → next history = some x → (next pre).isSome

/-- The query function is defined on this response history. -/
def QueryFunction.Dom (Q : QueryFunction X Y) (ys : List Y) : Prop :=
  (Q.next ys).isSome

/-- `q`-tractability: every history in the domain has length strictly below `q`. -/
def Tractable (q : ℕ) (Q : QueryFunction X Y) : Prop :=
  ∀ {ys : List Y}, Q.Dom ys → ys.length < q

/-- Non-adaptivity: at a fixed round, the next query is response-independent. -/
def NonAdaptive (Q : QueryFunction X Y) : Prop :=
  ∀ {ys zs : List Y}, ys.length = zs.length →
    Q.Dom ys → Q.Dom zs → Q.next ys = Q.next zs

/-- A chronological list of query/response pairs. -/
abbrev Transcript (X : Type u) (Y : Type v) := List (X × Y)

def responses (tr : Transcript X Y) : List Y := tr.map Prod.snd

def queries (tr : Transcript X Y) : List X := tr.map Prod.fst

/-- Run a query function against a total system for at most `fuel` rounds. -/
noncomputable def interact (Q : QueryFunction X Y) (S : System X Y) :
    ℕ → Transcript X Y → Transcript X Y
  | 0, tr => tr
  | fuel + 1, tr =>
      match Q.next (responses tr) with
      | none => tr
      | some x =>
          let xs := queries tr ++ [x]
          let y := S (NonemptyHistory.ofList xs (by simp [xs, queries]))
          interact Q S fuel (tr ++ [(x, y)])

/-- The complete interaction of a `q`-tractable query function. -/
noncomputable def transcript (q : ℕ) (Q : QueryFunction X Y)
    (S : System X Y) : Transcript X Y := interact Q S q []

theorem interact_length_le_add (Q : QueryFunction X Y) (S : System X Y)
    (fuel : ℕ) (tr : Transcript X Y) :
    (interact Q S fuel tr).length ≤ tr.length + fuel := by
  induction fuel generalizing tr with
  | zero => simp [interact]
  | succ fuel ih =>
      cases hnext : Q.next (responses tr) with
      | none => simp [interact, hnext]
      | some x =>
        simp only [interact, hnext]
        let xs := queries tr ++ [x]
        let y := S (NonemptyHistory.ofList xs (by simp [xs, queries]))
        have h := ih (tr := tr ++ [(x, y)])
        simp only [List.length_append, List.length_cons, List.length_nil] at h ⊢
        change (interact Q S fuel (tr ++ [(x, y)])).length ≤ _
        omega

theorem transcript_length_le (q : ℕ) (Q : QueryFunction X Y)
    (S : System X Y) : (transcript q Q S).length ≤ q := by
  simpa [transcript] using interact_length_le_add Q S q []

/-- The transcript universe `T(Q)` generated by all total systems. -/
def TranscriptUniverse (q : ℕ) (Q : QueryFunction X Y) :
    Set (Transcript X Y) := {tr | ∃ S, transcript q Q S = tr}

/-- Distribution on transcripts induced by a random system. -/
noncomputable def transcriptDistribution (q : ℕ) (Q : QueryFunction X Y)
    (S : RandomSystem X Y) : PMF (Transcript X Y) :=
  S.map (transcript q Q)

@[simp]
theorem transcriptDistribution_pure (q : ℕ) (Q : QueryFunction X Y)
    (S : System X Y) :
    transcriptDistribution q Q (PMF.pure S) = PMF.pure (transcript q Q S) := by
  simp [transcriptDistribution, PMF.pure_map]

/-- A deterministic `q`-query distinguisher `(Q,d)`. -/
structure DeterministicDistinguisher (q : ℕ) (X : Type u) (Y : Type v) where
  query : QueryFunction X Y
  tractable : Tractable q query
  decision : Transcript X Y → Bool

/-- A randomized distinguisher is a distribution on deterministic pairs `(Q,d)`. -/
abbrev Distinguisher (q : ℕ) (X : Type u) (Y : Type v) :=
  PMF (DeterministicDistinguisher q X Y)

/-- `T(Q_A)`: the union of transcript universes over queries in `A`'s support. -/
def DistinguisherTranscriptUniverse (A : Distinguisher q X Y) :
    Set (Transcript X Y) :=
  {tr | ∃ a, A a ≠ 0 ∧ tr ∈ TranscriptUniverse q a.query}

/-- Acceptance probability of a deterministic distinguisher against a system. -/
noncomputable def acceptanceProbability (A : DeterministicDistinguisher q X Y)
    (S : RandomSystem X Y) : ℝ :=
  (((transcriptDistribution q A.query S).map A.decision) true).toReal

/-- Equation (1): distinguishing advantage for a deterministic distinguisher. -/
noncomputable def distinguishingAdvantage
    (S₀ S₁ : RandomSystem X Y) (A : DeterministicDistinguisher q X Y) : ℝ :=
  |acceptanceProbability A S₀ - acceptanceProbability A S₁|

/-- Normalized `ℓ₁` distance, i.e. statistical distance, between PMFs. -/
noncomputable def statisticalDistance (p r : PMF Ω) : ℝ :=
  (1 / 2 : ℝ) * ∑' x, |(p x).toReal - (r x).toReal|

/-- Acceptance probability after sampling the pair `(Q,d)` from `A`. -/
noncomputable def randomizedAcceptanceProbability
    (A : Distinguisher q X Y) (S : RandomSystem X Y) : ℝ :=
  ∑' a, (A a).toReal * acceptanceProbability a S

/-- Equation (1), including the paper's randomized distinguisher. -/
noncomputable def randomizedAdvantage
    (S₀ S₁ : RandomSystem X Y) (A : Distinguisher q X Y) : ℝ :=
  |randomizedAcceptanceProbability A S₀ -
    randomizedAcceptanceProbability A S₁|

@[simp]
theorem randomizedAcceptanceProbability_pure
    (a : DeterministicDistinguisher q X Y) (S : RandomSystem X Y) :
    randomizedAcceptanceProbability (PMF.pure a) S = acceptanceProbability a S := by
  classical
  rw [randomizedAcceptanceProbability, tsum_eq_single a]
  · simp
  · intro b hba
    simp [hba]

@[simp]
theorem randomizedAdvantage_pure
    (S₀ S₁ : RandomSystem X Y) (a : DeterministicDistinguisher q X Y) :
    randomizedAdvantage S₀ S₁ (PMF.pure a) =
      distinguishingAdvantage S₀ S₁ a := by
  simp [randomizedAdvantage, distinguishingAdvantage]

section PublicRandomSystem

/-- Tagged query space used to regard private and public interfaces as one system. -/
inductive TaggedQuery (Xprivate : Type u) (Xpublic : Type v)
  | privateQuery : Xprivate → TaggedQuery Xprivate Xpublic
  | publicQuery : Xpublic → TaggedQuery Xprivate Xpublic

/-- A correlated private/public pair is modeled as one system on tagged queries. -/
abbrev PrivatePublicRandomSystem (Xprivate : Type u) (Xpublic : Type v)
    (Y : Type*) := RandomSystem (TaggedQuery Xprivate Xpublic) Y

def isPrivate {Xprivate : Type u} {Xpublic : Type v}
    (x : TaggedQuery Xprivate Xpublic) : Bool :=
  match x with
  | .privateQuery _ => true
  | .publicQuery _ => false

def isPublic {Xprivate : Type u} {Xpublic : Type v}
    (x : TaggedQuery Xprivate Xpublic) : Bool := !isPrivate x

/-- Interface-level refinement of tractability from the end of Section 3.1. -/
def InterfaceTractable (qc qp : ℕ)
    (tr : Transcript (TaggedQuery Xprivate Xpublic) Y) : Prop :=
  (queries tr).countP isPrivate ≤ qc ∧
    (queries tr).countP isPublic ≤ qp

end PublicRandomSystem

end InformationTheoreticSecurity.Section31
